# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Sample.xcodeproj")
    build_app(workspace: "Sample.xcworkspace", scheme: "Sample")
    upload_to_testflight
  end

  lane :metric do
    sonar(
      project_version: ENV['BUILD_NUMBER'],
      project_key: "com.safetrust.swdk.demo",
      sources_path: '.',
      sonar_login: ENV['SONAR_KEY'],
      sonar_url: "http://10.13.2.243"
    )
  end
  lane :verify do
    cocoapods()    
    gym()
  end
  lane :release do
    increment_build_number(
      build_number: ENV['BUILD_NUMBER']
    )
    cocoapods()
    gym()
  end
  lane :internal_release do
    cocoapods()    
    gym(
      skip_profile_detection: true,
      export_options: {
        method: "ad-hoc",
        signingStyle: "manual",
        provisioningProfiles: {
          "com.safetrust.swdk.demo" => "Safetrust SWDK Demo - adhoc"
        }
      },
      xcargs: "ARCHS='arm64' VALID_ARCHS='arm64'",
      output_name: "SwdkTrustIssuer.ipa",
      output_directory: "InternalRelease",
      archive_path: "ArchiveData"
    )
  end
  lane :dev_build do
    cocoapods()
    gym(
      configuration: "Debug",
      export_options: {
        method: "development"
      },
      export_xcargs: "-allowProvisioningUpdates",
      xcargs: "ARCHS='arm64' VALID_ARCHS='arm64'",
      output_name: "SwdkTrustIssuer.ipa",
      output_directory: "InternalRelease",
      archive_path: "ArchiveData"
    )

  end
  
end


