# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample
  pod 'GoogleSignIn', '~> 5.0.2'

  pod 'PhoneNumberKit', '~> 2.6'

  pod 'FlagPhoneNumber', '0.7.2'

  pod 'SafetrustWalletDevelopmentKit', :path => '../../../safetrust.swdk.wallet/safetrust.swdk.distributions/'
  
end
