name: Hello World
on:
  push:
    branches: [master]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get today
        run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - name: Print hello world
        run: echo Hello World, today is $TODAY