name: Generate release notes and deploy

on:
  push:
    tags:
      - v0.0.1
      - v0.0.2

jobs:
  # generate-release-notes:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: input
  #       uses: yashanand1910/standard-release-notes@v1.2.1
  #       id: get_release_notes
  #       with:
  #         changelog_path: ./CHANGELOG.md # Optional
  #         version: ${{ github.ref }} # Required

  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate standard release note
        uses: yashanand1910/standard-release-notes@v1.2.1
        id: get_release_notes
        with:
          changelog_path: ./CHANGELOG.md # Optional
          version: ${{ github.ref }} # Required
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.get_release_notes.outputs.release_notes }}
          draft: false
          prerelease: false