name: Generate release notes flow
on:
  push:
    tags:
      - v0.0.1

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:2.0.1
      env:
        GITHUB_TOKEN: ${{ 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 }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"