name: Release

on:
  push:
    branches:
    - master
    - /*

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: checkout repo
      uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Install hub
      uses: geertvdc/setup-hub@master
      
    - name: Build & Release
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
      run: |
           version=$(hub release -L 1| awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}')
           echo $version
           #build api
           dotnet publish --configuration Release --output $HOME/artifacts/api
           cd $HOME/artifacts/api
           zip -r api-$version.zip .
           
           #build frontend
           cd $GITHUB_WORKSPACE/frontend/xpirit-beerxchange
           npm install
           npm run build-prod
           cd dist/xpirit-beerxchange
           zip -r frontend-$version.zip .
           cp frontend-$version.zip $HOME/artifacts/
           #create release
           cd $GITHUB_WORKSPACE
           hub release create -m $version -a $HOME/artifacts/api/api-$version.zip -a $HOME/artifacts/frontend-$version.zip $version